### ISSUE TITLE
A few channels are not working

### ISSUE THREAD

**Issue by bds3151** [d21spike/plugin.video.sling#26] opened 2021-03-18 02:19 UTC
I have a new issue on my Win10 Kodi 18.9 machines. Some of the Sling channels work and a few don't. When I click on the tile in Kodi for lets say History, it starts clocking and then stops and goes back to the Kodi home screen. The log reports an issue with Inputstream Adaptive - "could not open/parse mpdURL". Many other channels work fine. Seems like Sling changed a few channels as others like Science work fine. All channels work fine on the Sling Windows App. outside of Kodi. Anyone else see this?

**Comment by xags** [comment] 2021-03-20 13:58
@bds3151 Can you include a debug log? I have no issues playing either/any channels.

**Comment by bds3151** [comment] 2021-03-20 14:11
Log is at https://paste.kodi.tv/tinezuxino. Thanks for taking a look. So glad it's still being looked after.


-----Original Message-----

**Comment by d21spike** [comment] 2021-03-20 16:57
@bds3151 Glancing at your log, looks like Kodi fails to open the playlist file. Was the Slinger service running at the time of this log? 

If it was, can you have it running and try opening one of the links referenced below and paste your output?

```python
2021-03-20 07:05:10.261 T:15424   ERROR: 192.168.88.176 - - [20/Mar/2021 07:05:10] "GET /playlist.mpd?http://p-cdn1-803-cg14-linear-cbd46b77.movetv.com/clipslist/156/20210320T140000Z/20210320T150000Z.mpd HTTP/1.1" 200 -
2021-03-20 07:05:10.714 T:14536   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://192.168.88.176:9999/playlist.mpd?http://p-cdn1-803-cg14-linear-cbd46b77.movetv.com/clipslist/156/20210320T140000Z/20210320T150000Z.mpd)
2021-03-20 07:05:10.717 T:14536   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.sling/?url=http%3A%2F%2Fcbd46b77.cdn.cms.movetv.com%2Fcms%2Fapi%2Fchannels%2Fa0b2c49be7814fa4bf1e381b7f12ce55%2Fschedule%2Fnow%2Fplayback_info.qvt&mode=play&name=History]
```

In the meantime, I'll try to replicate this. Could you tell me, do you have Sling Orange or Blue? This would save me some time tracking down the channel.

**Comment by bds3151** [comment] 2021-03-20 17:12
I have sling Blue.

**Comment by bds3151** [comment] 2021-03-20 17:13
Slinger service was running.

**Comment by bds3151** [comment] 2021-03-20 17:15
The primary channels that I have identified as failing are Paramount, History, and Travel.

**Comment by bds3151** [comment] 2021-03-20 17:26
"If it was, can you have it running and try opening one of the links referenced below and paste your output?"
Since Slinger was running I'll assume you meant to turn it off and run again....https://paste.kodi.tv/imomahefin. The result was the same when I tried to open the Travel channel.

**Comment by bds3151** [comment] 2021-03-20 17:38
Or did you want me to try to open one of those links using a browser? I tried but was told I wasn't authorized.

**Comment by d21spike** [comment] 2021-03-21 11:54
@bds3151 Yup I wanted to see what the result of one the links was, just in case the addon was modifying them improperly.

Anyways, "I believe" version 0.0110 should address your issue. The changes are in this commit 755e12d5aa6547e878723b84f06ff6ad95fd8507. It's a temporary solution till I come up with a more permanent one.

**Comment by bds3151** [comment] 2021-03-21 16:21
I tried it and unfortunately had the same issue. Log is at https://paste.kodi.tv/iqiduyisag. Thanks again for looking into this.


-----Original Message-----

**Comment by d21spike** [comment] 2021-03-21 16:35
@bds3151 I've had to try to play the channel a few times in a row sometimes to get the license to update and playback to begin. Can you try the same and report back? As you can see mine is playing....
![image](https://user-images.githubusercontent.com/6399602/111912843-da01f200-8a41-11eb-9dad-76a757cf9267.png)


Also in add-on settings, make sure you enable Debugging
![image](https://user-images.githubusercontent.com/6399602/111912815-b474e880-8a41-11eb-972d-f86e613cece0.png)

**Comment by bds3151** [comment] 2021-03-21 17:14
I've tried 5 times in a row and nothing. Here is a fresh log... https://paste.kodi.tv/ojujohapom


-----Original Message-----

**Comment by bds3151** [comment] 2021-03-22 04:22
Update - I found my problem. It was DNS on my router. I took out the fixed addresses and let it get them from my provider. Thanks again for all your help. Strange issue where DNS would affect only a few channels.

**Comment by d21spike** [comment] 2021-03-22 11:08
Interesting, particularly since when I opened a qmx file link that used `p-cdn3` server like HISTORY did. I was greeted with a message that basically said my region didn't have access to the content. Once I change the server to something like `p-cdn1` it worked fine no problem. Checked again today and both work. I have a feeling they are working on their restrictions.

Either way, glad it's working for you.

**Comment by bds3151** [comment] 2021-03-22 12:40
I originally used Unblockr DNS and I changed this back and forth between Frontier supplied DNS and it only worked with the Frontier DNS.

**Comment by GreatOwle** [comment] 2021-03-24 06:31
I have fixed this problem. The root cause is that InputStreamHelper has been deprecated. I've got code that works with KODI matrix but for the life of me can't figure out how to share with all of you. VERY FRUSTRATING.

**Comment by d21spike** [comment] 2021-03-24 11:00
Gotcha, definitely a possibility. I think in this case there were two issues since I also had a message. Going to close the issue now if that's alright.

**Comment by bds3151** [comment] 2021-03-24 13:56
It's fine to close the issue.


-----Original Message-----

**Closed** 2021-03-24 14:16 UTC
